<?php
$config->maps['$version'] = '3.0 beta4';
$config->maps['pager'] = array('type' => 'object', 'name' => 'pager');
$config->maps['pager']['dataType'][] = array('name' => 'gid', 'type' => 'basic');
$config->maps['pager']['dataType'][] = array('name' => 'recTotal', 'type' => 'basic');
$config->maps['pager']['dataType'][] = array('name' => 'pageID', 'type' => 'basic');
$config->maps['pager']['dataType'][] = array('name' => 'recPerPage', 'type' => 'basic');
$config->maps['pager']['dataType'][] = array('name' => 'continued', 'type' => 'basic');
$config->maps['memberStatus'] = array('name' => 'memberStatus', 'type' => 'basic', 'options' => array('','offline','online','busy','away'), 'dataType' => array());
$config->maps['member'] = array('type' => 'object', 'name' => 'member');
$config->maps['member']['dataType'][] = array('name' => 'id', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'account', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'status', 'type' => $config->maps['memberStatus']['type'], 'options' => $config->maps['memberStatus']['options'], 'dataType' => $config->maps['memberStatus']['dataType']);
$config->maps['member']['dataType'][] = array('name' => 'realname', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'avatar', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'gender', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'dept', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'role', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'signed', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'email', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'mobile', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'phone', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'site', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'admin', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'realnames', 'type' => 'basic');
$config->maps['member']['dataType'][] = array('name' => 'deleted', 'type' => 'basic');
$config->maps['userUpdateData'] = array('type' => 'object', 'name' => 'userUpdateData');
$config->maps['userUpdateData']['dataType'][] = array('name' => 'account', 'type' => 'basic');
$config->maps['userUpdateData']['dataType'][] = array('name' => 'status', 'type' => $config->maps['memberStatus']['type'], 'options' => $config->maps['memberStatus']['options'], 'dataType' => $config->maps['memberStatus']['dataType']);
$config->maps['userUpdateData']['dataType'][] = array('name' => 'password', 'type' => 'basic');
$config->maps['extension'] = array('type' => 'object', 'name' => 'extension');
$config->maps['extension']['dataType'][] = array('name' => 'name', 'type' => 'basic');
$config->maps['extension']['dataType'][] = array('name' => 'entryID', 'type' => 'basic');
$config->maps['extension']['dataType'][] = array('name' => 'md5', 'type' => 'basic');
$config->maps['extension']['dataType'][] = array('name' => 'download', 'type' => 'basic');
$config->maps['extension']['dataType'][] = array('name' => 'displayName', 'type' => 'basic');
$config->maps['extension']['dataType'][] = array('name' => 'abbrName', 'type' => 'basic');
$config->maps['extension']['dataType'][] = array('name' => 'webViewUrl', 'type' => 'basic');
$config->maps['extension']['dataType'][] = array('name' => 'logo', 'type' => 'basic');
$config->maps['extension']['dataType'][] = array('name' => 'data', 'type' => 'basic');
$config->maps['extensionList'] = array('name' => 'extensionList', 'type' => 'list', 'dataType' => $config->maps['extension']);
$config->maps['notification'] = array('type' => 'object', 'name' => 'notification');
$config->maps['notification']['dataType'][] = array('name' => 'id', 'type' => 'basic');
$config->maps['notification']['dataType'][] = array('name' => 'gid', 'type' => 'basic');
$config->maps['notification']['dataType'][] = array('name' => 'title', 'type' => 'basic');
$config->maps['notification']['dataType'][] = array('name' => 'date', 'type' => 'basic');
$config->maps['notification']['dataType'][] = array('name' => 'sender', 'type' => 'basic');
$config->maps['notification']['dataType'][] = array('name' => 'actions', 'type' => 'basic');
$config->maps['notification']['dataType'][] = array('name' => 'url', 'type' => 'basic');
$config->maps['notification']['dataType'][] = array('name' => 'cgid', 'type' => 'basic');
$config->maps['notification']['dataType'][] = array('name' => 'content', 'type' => 'basic');
$config->maps['notification']['dataType'][] = array('name' => 'subtitle', 'type' => 'basic');
$config->maps['notification']['dataType'][] = array('name' => 'contentType', 'type' => 'basic', 'options' => array('text','plain'));
$config->maps['notification']['dataType'][] = array('name' => 'type', 'type' => 'basic', 'options' => array('notification'));
$config->maps['chatMessage'] = array('type' => 'object', 'name' => 'chatMessage');
$config->maps['chatMessage']['dataType'][] = array('name' => 'gid', 'type' => 'basic');
$config->maps['chatMessage']['dataType'][] = array('name' => 'cgid', 'type' => 'basic');
$config->maps['chatMessage']['dataType'][] = array('name' => 'user', 'type' => 'basic');
$config->maps['chatMessage']['dataType'][] = array('name' => 'date', 'type' => 'basic');
$config->maps['chatMessage']['dataType'][] = array('name' => 'content', 'type' => 'basic');
$config->maps['chatMessage']['dataType'][] = array('name' => 'id', 'type' => 'basic');
$config->maps['chatMessage']['dataType'][] = array('name' => 'order', 'type' => 'basic');
$config->maps['chatMessage']['dataType'][] = array('name' => 'data', 'type' => 'basic');
$config->maps['chatMessage']['dataType'][] = array('name' => 'type', 'type' => 'basic', 'options' => array('','normal','broadcast','notification'));
$config->maps['chatMessage']['dataType'][] = array('name' => 'contentType', 'type' => 'basic', 'options' => array('','text','plain','image','file','emoticon','code','object'));
$config->maps['chatMessage']['dataType'][] = array('name' => 'deleted', 'type' => 'basic');
$config->maps['chatMessageList'] = array('name' => 'chatMessageList', 'type' => 'list', 'dataType' => $config->maps['chatMessage']);
$config->maps['sendingChatMessage'] = array('type' => 'object', 'name' => 'sendingChatMessage');
$config->maps['sendingChatMessage']['dataType'][] = array('name' => 'gid', 'type' => 'basic');
$config->maps['sendingChatMessage']['dataType'][] = array('name' => 'cgid', 'type' => 'basic');
$config->maps['sendingChatMessage']['dataType'][] = array('name' => 'user', 'type' => 'basic');
$config->maps['sendingChatMessage']['dataType'][] = array('name' => 'content', 'type' => 'basic');
$config->maps['sendingChatMessage']['dataType'][] = array('name' => 'order', 'type' => 'basic');
$config->maps['sendingChatMessage']['dataType'][] = array('name' => 'data', 'type' => 'basic');
$config->maps['sendingChatMessage']['dataType'][] = array('name' => 'type', 'type' => 'basic', 'options' => array('','normal','broadcast','notification'));
$config->maps['sendingChatMessage']['dataType'][] = array('name' => 'contentType', 'type' => 'basic', 'options' => array('','text','plain','image','file','emoticon','code','object'));
$config->maps['sendingChatMessage']['dataType'][] = array('name' => 'date', 'type' => 'basic');
$config->maps['sendingChatMessage']['dataType'][] = array('name' => 'deleted', 'type' => 'basic');
$config->maps['sendingChatMessageList'] = array('name' => 'sendingChatMessageList', 'type' => 'list', 'dataType' => $config->maps['sendingChatMessage']);
$config->maps['chat'] = array('type' => 'object', 'name' => 'chat');
$config->maps['chat']['dataType'][] = array('name' => 'gid', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'members', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'createdDate', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'createdBy', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'id', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'name', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'lastActiveTime', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'public', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'star', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'freeze', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'mute', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'hide', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'editedDate', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'type', 'type' => 'basic', 'options' => array('group','one2one','system','robot'));
$config->maps['chat']['dataType'][] = array('name' => 'dismissDate', 'type' => 'basic');
$config->maps['chat']['dataType'][] = array('name' => 'committers', 'type' => 'basic', 'options' => array('','$ADMINS','$ALL'));
$config->maps['chat']['dataType'][] = array('name' => 'admins', 'type' => 'basic');
$config->maps['chatList'] = array('name' => 'chatList', 'type' => 'list', 'dataType' => $config->maps['chat']);
$config->maps['basicPack'] = array('type' => 'object', 'name' => 'basicPack');
$config->maps['basicPack']['dataType'][] = array('name' => 'rid', 'type' => 'basic');
$config->maps['basicPack']['dataType'][] = array('name' => 'method', 'type' => 'basic', 'options' => array('messagesend','syssessionid','usergetlist','chatgetlist','userlogin','userlogout','userupdate','usersyncsettings','userkickoff','messageretract','messageupdate','chattyping','chatcreate','chatrename','chatinvite','chatkick','chatjoin','chatleave','chatstar','chatunstar','chatmute','chatunmute','chatfreeze','chatunfreeze','chathide','chatdismiss','chatgethistory','chatgetpubliclist','chatsetcategory','chatrenamecategory','chatdeletecategory','chatsetadmin','chatremoveadmin','chatsetcommitters','chatsetvisibility','syncusers','syncnotifications','syncofflinemessages','extensiongetlist','fileupload','filedownload','usersetdevicetoken','sysgetserverinfo','sysserverstart','ping'));
$config->maps['basicPack']['dataType'][] = array('name' => 'module', 'type' => 'basic', 'options' => array('','im','server','sys','chat','entry','user','extension'));
$config->maps['requestPack'] = $config->maps['basicPack'];
$config->maps['requestPack']['dataType'][] = array('name' => 'params', 'type' => 'basic');
$config->maps['requestPack']['dataType'][] = array('name' => 'userID', 'type' => 'basic');
$config->maps['requestPack']['dataType'][] = array('name' => 'device', 'type' => 'basic', 'options' => array('desktop','mobile'));
$config->maps['requestPack']['dataType'][] = array('name' => 'lang', 'type' => 'basic', 'options' => array('zh-cn','zh-tw','en'));
$config->maps['requestPack']['dataType'][] = array('name' => 'version', 'type' => 'basic', 'options' => array('3.0 beta2','3.0 beta3','3.0.0','3.1.0'));
$config->maps['responsePack'] = $config->maps['basicPack'];
$config->maps['responsePack']['dataType'][] = array('name' => 'data', 'type' => 'basic');
$config->maps['responsePack']['dataType'][] = array('name' => 'result', 'type' => 'basic', 'options' => array('success','fail'));
$config->maps['responsePack']['dataType'][] = array('name' => 'message', 'type' => 'basic');
$config->maps['messageResponsePack'] = $config->maps['responsePack'];
$config->maps['messageResponsePack']['dataType'][] = array('name' => 'message', 'type' => 'basic');
$config->maps['messageResponsePack']['dataType'][] = array('name' => 'code', 'type' => 'basic');
$config->maps['memberResponsePack'] = $config->maps['responsePack'];
$config->maps['memberResponsePack']['dataType'][3] = array('name' => 'data', 'type' => $config->maps['member']['type'], 'dataType' => $config->maps['member']['dataType']);
$config->maps['chatResponsePack'] = $config->maps['responsePack'];
$config->maps['chatResponsePack']['dataType'][3] = array('name' => 'data', 'type' => $config->maps['chat']['type'], 'dataType' => $config->maps['chat']['dataType']);
$config->maps['chatListResponsePack'] = $config->maps['responsePack'];
$config->maps['chatListResponsePack']['dataType'][3] = array('name' => 'data', 'type' => $config->maps['chatList']['type'], 'dataType' => $config->maps['chatList']['dataType']);
$config->maps['messageListRequestPack'] = $config->maps['requestPack'];
$config->maps['messageListRequestPack']['dataType'][3] = array('name' => 'params', 'type' => 'list', 'dataType' => $config->maps['sendingChatMessageList']);
$config->maps['messageListResponsePack'] = $config->maps['responsePack'];
$config->maps['messageListResponsePack']['dataType'][3] = array('name' => 'data', 'type' => $config->maps['chatMessageList']['type'], 'dataType' => $config->maps['chatMessageList']['dataType']);
$config->maps['userloginRequest'] = $config->maps['requestPack'];
$config->maps['userloginRequest']['name'] = 'userloginRequest';
$config->maps['userloginResponse'] = $config->maps['memberResponsePack'];
$config->maps['userloginResponse']['name'] = 'userloginResponse';
$config->maps['userlogoutRequest'] = $config->maps['requestPack'];
$config->maps['userlogoutRequest']['name'] = 'userlogoutRequest';
$config->maps['userlogoutResponse'] = $config->maps['memberResponsePack'];
$config->maps['userlogoutResponse']['name'] = 'userlogoutResponse';
$config->maps['usergetlistRequest'] = $config->maps['requestPack'];
$config->maps['usergetlistRequest']['name'] = 'usergetlistRequest';
$config->maps['usergetlistResponse'] = $config->maps['responsePack'];
$config->maps['usergetlistResponse']['dataType'][3] = array('name' => 'data', 'type' => 'list', 'dataType' => $config->maps['member']);
$config->maps['usergetlistResponse']['dataType'][] = array('name' => 'roles', 'type' => 'basic');
$config->maps['usergetlistResponse']['dataType'][] = array('name' => 'depts', 'type' => 'basic');
$config->maps['usergetdeletedRequest'] = $config->maps['usergetlistRequest'];
$config->maps['usergetdeletedRequest']['name'] = 'usergetdeletedRequest';
$config->maps['usergetdeletedResponse'] = $config->maps['usergetlistResponse'];
$config->maps['usergetdeletedResponse']['name'] = 'usergetdeletedResponse';
$config->maps['chatgetlistRequest'] = $config->maps['requestPack'];
$config->maps['chatgetlistRequest']['name'] = 'chatgetlistRequest';
$config->maps['chatgetlistResponse'] = $config->maps['chatListResponsePack'];
$config->maps['chatgetlistResponse']['name'] = 'chatgetlistResponse';
$config->maps['messagesendRequest'] = $config->maps['messageListRequestPack'];
$config->maps['messagesendRequest']['name'] = 'messagesendRequest';
$config->maps['messagesendResponse'] = $config->maps['messageListResponsePack'];
$config->maps['messagesendResponse']['name'] = 'messagesendResponse';
$config->maps['messageretractRequest'] = $config->maps['messageListRequestPack'];
$config->maps['messageretractRequest']['name'] = 'messageretractRequest';
$config->maps['messageretractResponse'] = $config->maps['messageListResponsePack'];
$config->maps['messageretractResponse']['name'] = 'messageretractResponse';
$config->maps['syncofflinemessagesRequest'] = $config->maps['requestPack'];
$config->maps['syncofflinemessagesRequest']['name'] = 'syncofflinemessagesRequest';
$config->maps['syncofflinemessagesResponse'] = $config->maps['messageListResponsePack'];
$config->maps['syncofflinemessagesResponse']['name'] = 'syncofflinemessagesResponse';
$config->maps['syncnotificationsRequest'] = $config->maps['requestPack'];
$config->maps['syncnotificationsRequest']['name'] = 'syncnotificationsRequest';
$config->maps['syncnotificationsResponse'] = $config->maps['responsePack'];
$config->maps['syncnotificationsResponse']['dataType'][3] = array('name' => 'data', 'type' => 'list', 'dataType' => $config->maps['notification']);
$config->maps['userupdateRequest'] = $config->maps['requestPack'];
$config->maps['userupdateRequest']['dataType'][3] = array('name' => 'params', 'type' => 'list', 'dataType' => $config->maps['userUpdateData']);
$config->maps['usersyncsettingsRequest'] = $config->maps['requestPack'];
$config->maps['usersyncsettingsRequest']['name'] = 'usersyncsettingsRequest';
$config->maps['usersyncsettingsResponse'] = $config->maps['responsePack'];
$config->maps['usersyncsettingsResponse']['name'] = 'usersyncsettingsResponse';
$config->maps['userupdateResponse'] = $config->maps['messageResponsePack'];
$config->maps['userupdateResponse']['name'] = 'userupdateResponse';
$config->maps['usersetdevicetokenRequest'] = $config->maps['requestPack'];
$config->maps['usersetdevicetokenRequest']['name'] = 'usersetdevicetokenRequest';
$config->maps['usersetdevicetokenResponse'] = $config->maps['responsePack'];
$config->maps['usersetdevicetokenResponse']['name'] = 'usersetdevicetokenResponse';
$config->maps['chatcreateRequest'] = $config->maps['requestPack'];
$config->maps['chatcreateRequest']['name'] = 'chatcreateRequest';
$config->maps['chatcreateResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatcreateResponse']['name'] = 'chatcreateResponse';
$config->maps['chatjoinRequest'] = $config->maps['requestPack'];
$config->maps['chatjoinRequest']['name'] = 'chatjoinRequest';
$config->maps['chatjoinResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatjoinResponse']['name'] = 'chatjoinResponse';
$config->maps['chatleaveRequest'] = $config->maps['requestPack'];
$config->maps['chatleaveRequest']['name'] = 'chatleaveRequest';
$config->maps['chatleaveResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatleaveResponse']['name'] = 'chatleaveResponse';
$config->maps['chatrenameRequest'] = $config->maps['requestPack'];
$config->maps['chatrenameRequest']['name'] = 'chatrenameRequest';
$config->maps['chatrenameResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatrenameResponse']['name'] = 'chatrenameResponse';
$config->maps['chatinviteRequest'] = $config->maps['requestPack'];
$config->maps['chatinviteRequest']['name'] = 'chatinviteRequest';
$config->maps['chatinviteResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatinviteResponse']['name'] = 'chatinviteResponse';
$config->maps['chatkickRequest'] = $config->maps['requestPack'];
$config->maps['chatkickRequest']['name'] = 'chatkickRequest';
$config->maps['chatkickResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatkickResponse']['name'] = 'chatkickResponse';
$config->maps['chatstarRequest'] = $config->maps['requestPack'];
$config->maps['chatstarRequest']['name'] = 'chatstarRequest';
$config->maps['chatstarResponse'] = $config->maps['responsePack'];
$config->maps['chatstarResponse']['name'] = 'chatstarResponse';
$config->maps['chatunstarRequest'] = $config->maps['requestPack'];
$config->maps['chatunstarRequest']['name'] = 'chatunstarRequest';
$config->maps['chatunstarResponse'] = $config->maps['responsePack'];
$config->maps['chatunstarResponse']['name'] = 'chatunstarResponse';
$config->maps['chathideRequest'] = $config->maps['requestPack'];
$config->maps['chathideRequest']['name'] = 'chathideRequest';
$config->maps['chathideResponse'] = $config->maps['responsePack'];
$config->maps['chathideResponse']['name'] = 'chathideResponse';
$config->maps['chatsetvisibilityRequest'] = $config->maps['requestPack'];
$config->maps['chatsetvisibilityRequest']['name'] = 'chatsetvisibilityRequest';
$config->maps['chatsetvisibilityResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatsetvisibilityResponse']['name'] = 'chatsetvisibilityResponse';
$config->maps['chatsetadminRequest'] = $config->maps['requestPack'];
$config->maps['chatsetadminRequest']['name'] = 'chatsetadminRequest';
$config->maps['chatsetadminResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatsetadminResponse']['name'] = 'chatsetadminResponse';
$config->maps['chatremoveadminRequest'] = $config->maps['requestPack'];
$config->maps['chatremoveadminRequest']['name'] = 'chatremoveadminRequest';
$config->maps['chatremoveadminResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatremoveadminResponse']['name'] = 'chatremoveadminResponse';
$config->maps['chatsetcommittersRequest'] = $config->maps['requestPack'];
$config->maps['chatsetcommittersRequest']['name'] = 'chatsetcommittersRequest';
$config->maps['chatsetcommittersResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatsetcommittersResponse']['name'] = 'chatsetcommittersResponse';
$config->maps['chatdismissRequest'] = $config->maps['requestPack'];
$config->maps['chatdismissRequest']['name'] = 'chatdismissRequest';
$config->maps['chatdismissResponse'] = $config->maps['chatResponsePack'];
$config->maps['chatdismissResponse']['name'] = 'chatdismissResponse';
$config->maps['chatgethistoryRequest'] = $config->maps['requestPack'];
$config->maps['chatgethistoryRequest']['name'] = 'chatgethistoryRequest';
$config->maps['chatgethistoryResponse'] = $config->maps['messageListResponsePack'];
$config->maps['chatgethistoryResponse']['dataType'][] = array('name' => 'pager', 'type' => $config->maps['pager']['type'], 'dataType' => $config->maps['pager']['dataType']);
$config->maps['chatmuteRequest'] = $config->maps['requestPack'];
$config->maps['chatmuteRequest']['name'] = 'chatmuteRequest';
$config->maps['chatmuteResponse'] = $config->maps['responsePack'];
$config->maps['chatmuteResponse']['name'] = 'chatmuteResponse';
$config->maps['chatunmuteRequest'] = $config->maps['requestPack'];
$config->maps['chatunmuteRequest']['name'] = 'chatunmuteRequest';
$config->maps['chatunmuteResponse'] = $config->maps['responsePack'];
$config->maps['chatunmuteResponse']['name'] = 'chatunmuteResponse';
$config->maps['chatfreezeRequest'] = $config->maps['requestPack'];
$config->maps['chatfreezeRequest']['name'] = 'chatfreezeRequest';
$config->maps['chatfreezeResponse'] = $config->maps['responsePack'];
$config->maps['chatfreezeResponse']['name'] = 'chatfreezeResponse';
$config->maps['chatunfreezeRequest'] = $config->maps['requestPack'];
$config->maps['chatunfreezeRequest']['name'] = 'chatunfreezeRequest';
$config->maps['chatunfreezeResponse'] = $config->maps['responsePack'];
$config->maps['chatunfreezeResponse']['name'] = 'chatunfreezeResponse';
$config->maps['chatsetcategoryRequest'] = $config->maps['requestPack'];
$config->maps['chatsetcategoryRequest']['name'] = 'chatsetcategoryRequest';
$config->maps['chatsetcategoryResponse'] = $config->maps['responsePack'];
$config->maps['chatsetcategoryResponse']['name'] = 'chatsetcategoryResponse';
$config->maps['chatrenamecategoryRequest'] = $config->maps['requestPack'];
$config->maps['chatrenamecategoryRequest']['name'] = 'chatrenamecategoryRequest';
$config->maps['chatrenamecategoryResponse'] = $config->maps['responsePack'];
$config->maps['chatrenamecategoryResponse']['name'] = 'chatrenamecategoryResponse';
$config->maps['chatdeletecategoryRequest'] = $config->maps['requestPack'];
$config->maps['chatdeletecategoryRequest']['name'] = 'chatdeletecategoryRequest';
$config->maps['chatdeletecategoryResponse'] = $config->maps['responsePack'];
$config->maps['chatdeletecategoryResponse']['name'] = 'chatdeletecategoryResponse';
$config->maps['chatgetpubliclistRequest'] = $config->maps['requestPack'];
$config->maps['chatgetpubliclistRequest']['name'] = 'chatgetpubliclistRequest';
$config->maps['chatgetpubliclistResponse'] = $config->maps['chatListResponsePack'];
$config->maps['chatgetpubliclistResponse']['name'] = 'chatgetpubliclistResponse';
$config->maps['extensiongetlistRequest'] = $config->maps['requestPack'];
$config->maps['extensiongetlistRequest']['name'] = 'extensiongetlistRequest';
$config->maps['extensiongetlistResponse'] = $config->maps['responsePack'];
$config->maps['extensiongetlistResponse']['dataType'][3] = array('name' => 'data', 'type' => $config->maps['extensionList']['type'], 'dataType' => $config->maps['extensionList']['dataType']);
$config->maps['entry/visitRequest'] = $config->maps['requestPack'];
$config->maps['entry/visitRequest']['dataType'][3] = array('name' => 'params', 'type' => 'basic');
$config->maps['entry/visitResponse'] = $config->maps['responsePack'];
$config->maps['entry/visitResponse']['name'] = 'entry/visitResponse';
$config->maps['todoupsertRequest'] = $config->maps['requestPack'];
$config->maps['todoupsertRequest']['name'] = 'todoupsertRequest';
$config->maps['todoupsertResponse'] = $config->maps['responsePack'];
$config->maps['todoupsertResponse']['name'] = 'todoupsertResponse';
$config->maps['errormessageResponse'] = $config->maps['messageResponsePack'];
$config->maps['errormessageResponse']['name'] = 'errormessageResponse';
